name: Publish HTML Page
on:
  push:

permissions:
  pages: write
  id-token: write

jobs:
  PublishHTML:
    name: Publish Latest Rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - name: Generate bundle.js
        run: go generate ./internal/rulehtml/web
      - name: Build mtg-html-rules
        run: go build .
      - name: Make _site directory
        run: mkdir _site _site/images
      - name: Generate HTML file
        run: ./mtg-html-rules --output _site/index.html
      - name: Copy favicon to _site
        run: cp ./web/assets/favicon.png _site/images/favicon.png
      - name: Copy logo to _site
        run: cp ./web/assets/logo.png _site/images/logo.png
      - uses: actions/upload-pages-artifact@v3
      - uses: actions/deploy-pages@v4
